
[dialogs]
confirm = "Confermi?"
error   = "Errore"
ok      = "Ok"
cancel  = "Annulla"

[dialogs.chapter]
add    = "Aggiungi paragrafo"
edit   = "Modifica paragrafo"
delete = "Il paragrafo “%1” verrà eliminato"
exist  = "Questo paragrafo esiste già"

name   = "Key*"
title  = "Titolo"
group  = "Gruppo*"
hint   = "*Key e Gruppo dovrebbero contenere solo caratteri alfanumerici (a-z, A-Z, 0-9)"


[dialogs.newbook]
new    = "Crea un nuovo Libro"
title  = "Titolo"
author = "Autore"
hint   = "Puoi recuperare il libro precedente da <b>File -> Sessioni recenti</b>"

[dialogs.newfirebook]
new    = "Crea o accedi a un Libro Collaborativo"
book   = "Nome libro"
getStarted = """Con questa funzione puoi collegare Magebook al tuo account Google, così da creare libri che si possono modificare in simultanea, proprio come i Documenti Google.<br>Prima di iniziare, dovrai collegare Magebook al tuo account <a target="_blank" href="https://librogamesland.github.io/magebook/#/?id=progetti-collaborativi">seguendo questa guida</a>."""

[dialogs.shuffle]
title      = "Rimescola"
hint       = "Rimescola i paragrafi con chiave numerica. Puoi scegliere di mescolare solo i paragrafi che fanno parte di alcuni gruppi, o di escludere i paragrafi con determinati simboli. Per sicurezza, dovresti salvare una copia del libro prima di mescolare."
group      = "Filtro gruppi"
flags      = "Escludi simboli"
savecopy   = "Salva una copia"

[dialogs.lock]
title      = "Attenzione"
text       = "Un'altra tab ha modificato i dati di questa sessione. Se sovrascrivi, quei cambiamenti verranno persi. Se vuoi mantenere entrambe le versioni, puoi creare una nuova sessione e recuperare quella vecchia con <br><b>File -> Sessioni recenti</b>."
new        = "Apri nuova sessione"
overwrite  = "Sovrascrivi"

[dialogs.graph]
loading    = "Caricamento grafo..."
open       = "Apri un una nuova pagina"


[navbar.file]
title      = "File"
new        = "Nuovo"
newFire    = "Nuovo collaborativo"
share      = "Condividi"
open       = "Apri..."
save       = "Salva"
recover    = "Sessioni recenti"

[navbar.book]
title   = "Libro"
graph   = "Visualizza grafico"
shuffle = "Rimescola"
compact = "Compatta paragrafi"
sort    = "Riordina paragrafi"


[navbar.export]
title = "Esporta"
docx  = "Word (.docx)"
fodt  = "Libreoffice (.fodt)"
xlgc  = "LibroGameCreator 3"
json  = "Json"
vuejs = "Vue.js"

[navbar.help]
title     = "Aiuto"
guide     = "Guida"
guidefile = "https://librogamesland.github.io/magebook" 
forum     = "Forum Lgl"
about     = "Info"

[sidemenu]
toggle    = "Apri menu laterale"
chapters  = "Paragrafi"
allgroup  = "Tutti i paragrafi"
allgrouperrors  = "Senza entrata/uscita"
linkshere = "Link al par."

[sidemenu.actions]
goback   = "Vai indietro"
add      = "Aggiungi entità (ctrl+R)"
edit     = "Modifica entità (ctrl+E)"
delete   = "Elimina entità (ctrl+D)"


[editor.buttons]
find = "Cerca (ctrl+F)"
undo = "Annulla ultimo cambiamento (ctrl+Z)"
redo = "Ripristina ultimo cambiamento (ctrl+shift+Z)"
quicklink  = "Link al primo paragrafo disponibile (ctrl+K)"
link  = "Aggiungi link (ctrl+L)"


[about]
contact = "Contattami"
text = """
Magebook è un editor di librogame sviluppato da <b>Luca Fabbian</b> con il supporto della community di Lgl,
ispirato a LibroGameCreator3 di <b>Matteo Poropat</b>."""


[books]
local = """
# Titolo
author: Nome e Cognome


### 1
Esempio di paragrafo. Puoi modificarlo sfruttando i tasti a destra.
Questo è un link verso il paragrafo [](#2). I link sono nel formato [Testo](#paragrafo), dove Testo è opzionale.


### Paragrafo con titolo {#2}
Questo è il secondo paragrafo. I paragrafi possono contenere anche testo in *corsivo* o **grassetto**.  Puoi anche usare <b>grassetto</b>, <i>corsivo</i>, o <u>sottolineato</u>.
"""
fire = """
# %1
author: Nome e Cognome


### 1
Questo è un libro collaborativo memorizzato sul tuo account Google e che può essere modificato da più persone contemporaneamente. Salva questa pagina fra i segnalibri del tuo browser e inviala a chi vuoi, vedrai le modifiche sincronizzate in tempo reale.
"""

[app]
openlocal    = "Crea o apri file"
openfire     = "Crea o accedi a un libro collaborativo"
chooseother  = "Apri un altro"