name: "Build, Test and Deploy"
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Test
        run: npm run test

      - name: Publish to npm registry
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

        
      - name: Prepare for github pages
        run: |
          rm -rf src .gitignore node_modules package.json package-lock.json \
            rollup.config.js tsconfig.json
          touch .nojekyll


      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: . # The folder the action should deploy.
          single-commit	: true
          clean: true
